// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ipRXAhycgRyMLpeNL9CS2QQlEpLH7ig',
    appId: '1:163279636095:web:b42050ab9e0a34cf15614a',
    messagingSenderId: '163279636095',
    projectId: 'authentication-4410e',
    authDomain: 'authentication-4410e.firebaseapp.com',
    storageBucket: 'authentication-4410e.appspot.com',
    measurementId: 'G-8N2RQYE1HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoLB_hrGWjpjOEgo21g9BUhPLH0iU79dc',
    appId: '1:163279636095:android:cb92911760ab5d5815614a',
    messagingSenderId: '163279636095',
    projectId: 'authentication-4410e',
    storageBucket: 'authentication-4410e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHOQ22wtK7veC4cW5Aio0PKerP0Kpta0A',
    appId: '1:163279636095:ios:dfd55d9e7528567715614a',
    messagingSenderId: '163279636095',
    projectId: 'authentication-4410e',
    storageBucket: 'authentication-4410e.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHOQ22wtK7veC4cW5Aio0PKerP0Kpta0A',
    appId: '1:163279636095:ios:dfd55d9e7528567715614a',
    messagingSenderId: '163279636095',
    projectId: 'authentication-4410e',
    storageBucket: 'authentication-4410e.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6ipRXAhycgRyMLpeNL9CS2QQlEpLH7ig',
    appId: '1:163279636095:web:614390d37153989815614a',
    messagingSenderId: '163279636095',
    projectId: 'authentication-4410e',
    authDomain: 'authentication-4410e.firebaseapp.com',
    storageBucket: 'authentication-4410e.appspot.com',
    measurementId: 'G-1G8J0L5CW0',
  );
}
